[tool.poetry]
name = "projects"
version = "0.3.0" # Also update in projects/__init__.py AND logger
description = "Interact with ets/gpa/... project files."
authors = ["Fabian Göttel <fabian.goettel@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
isort = "^5.10"
mypy = "^0.910"
pydocstyle = "^6.1.1"
pylint = "^2.11"
pytest = "^6.2"
pytest-asyncio = "^0.16"
pytest-cov = "^3.0"
pytest-mock = "^3.6"
pytest-profiling = "^1.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.10"

[tool.pydocstyle]
ignore = [
    "D202",
    "D203",
    "D213",
    "D416",
]

[tool.coverage]
source = ["projects"]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "def __str__",
    "if __name__ == .__main__.:",
    "pytest.main([.-x.])",
]