[tool.poetry]
name = "projects"
version = "0.4.0" # Also update in projects/__init__.py AND logger
description = "Interact with ets/gpa/... project files."
authors = ["Fabian Göttel <fabian.goettel@gmail.com>"]

[tool.poetry.dependencies]
python = "3.10"

[tool.poetry.dev-dependencies]
black = "*"
isort = "*"
mypy = "*"
pydocstyle = "*"
pylint = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "*"
pytest-mock = "*"
pytest-profiling = "*"
toml = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
asyncio_mode = "auto"
testpaths = [
    "test"
]

[tool.mypy]
python_version = "3.10"

[tool.pydocstyle]
ignore = [
    "D202",
    "D203",
    "D213",
    "D416",
]

[tool.coverage]
source = ["projects"]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "def __str__",
    "if __name__ == .__main__.:",
    "pytest.main([.-x.])",
]