"""Autogenerated by logger/codegen/gen_orm.py."""

from abc import abstractmethod
from datetime import datetime

from sqlalchemy import Column, types
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class KNXMixin:
    """Basic properties of each knx request."""

    id_ = Column(types.Integer, primary_key=True)
    time = Column(types.DateTime, default=datetime.utcnow)
    src = Column(types.String)
    dst = Column(types.String)
    name = Column(types.String)

    @property
    @abstractmethod
    def value(self):
        """Abstract placeholder for values."""

    def __repr__(self):
        """Return basic information about this entity (value, name, time, src, dst)."""
        return f"{self.__class__.__name__}(value={self.value}, name={self.name}, time={self.time} src={self.src}, dst={self.dst})"  # noqa: E501


class AbsoluteTemperature(KNXMixin, Base):
    """ORM for xknx 'DPTAbsoluteTemperature'.

    DType: DPST-14-69
    """

    __tablename__ = "absolutetemperature"
    value = Column(types.Float)


class Acceleration(KNXMixin, Base):
    """ORM for xknx 'DPTAcceleration'.

    DType: DPST-14-0
    """

    __tablename__ = "acceleration"
    value = Column(types.Float)


class AccelerationAngular(KNXMixin, Base):
    """ORM for xknx 'DPTAccelerationAngular'.

    DType: DPST-14-1
    """

    __tablename__ = "accelerationangular"
    value = Column(types.Float)


class ActivationEnergy(KNXMixin, Base):
    """ORM for xknx 'DPTActivationEnergy'.

    DType: DPST-14-2
    """

    __tablename__ = "activationenergy"
    value = Column(types.Float)


class ActiveEnergy(KNXMixin, Base):
    """ORM for xknx 'DPTActiveEnergy'.

    DType: DPST-13-10
    """

    __tablename__ = "activeenergy"
    value = Column(types.Integer)


class ActiveEnergykWh(KNXMixin, Base):
    """ORM for xknx 'DPTActiveEnergykWh'.

    DType: DPST-13-13
    """

    __tablename__ = "activeenergykwh"
    value = Column(types.Integer)


class Activity(KNXMixin, Base):
    """ORM for xknx 'DPTActivity'.

    DType: DPST-14-3
    """

    __tablename__ = "activity"
    value = Column(types.Float)


class Amplitude(KNXMixin, Base):
    """ORM for xknx 'DPTAmplitude'.

    DType: DPST-14-5
    """

    __tablename__ = "amplitude"
    value = Column(types.Float)


class Angle(KNXMixin, Base):
    """ORM for xknx 'DPTAngle'.

    DType: DPST-5-3
    """

    __tablename__ = "angle"
    value = Column(types.Integer)


class AngleDeg(KNXMixin, Base):
    """ORM for xknx 'DPTAngleDeg'.

    DType: DPST-14-7
    """

    __tablename__ = "angledeg"
    value = Column(types.Float)


class AngleRad(KNXMixin, Base):
    """ORM for xknx 'DPTAngleRad'.

    DType: DPST-14-6
    """

    __tablename__ = "anglerad"
    value = Column(types.Float)


class AngularFrequency(KNXMixin, Base):
    """ORM for xknx 'DPTAngularFrequency'.

    DType: DPST-14-34
    """

    __tablename__ = "angularfrequency"
    value = Column(types.Float)


class AngularMomentum(KNXMixin, Base):
    """ORM for xknx 'DPTAngularMomentum'.

    DType: DPST-14-8
    """

    __tablename__ = "angularmomentum"
    value = Column(types.Float)


class AngularVelocity(KNXMixin, Base):
    """ORM for xknx 'DPTAngularVelocity'.

    DType: DPST-14-9
    """

    __tablename__ = "angularvelocity"
    value = Column(types.Float)


class ApparantEnergy(KNXMixin, Base):
    """ORM for xknx 'DPTApparantEnergy'.

    DType: DPST-13-11
    """

    __tablename__ = "apparantenergy"
    value = Column(types.Integer)


class ApparantEnergykVAh(KNXMixin, Base):
    """ORM for xknx 'DPTApparantEnergykVAh'.

    DType: DPST-13-14
    """

    __tablename__ = "apparantenergykvah"
    value = Column(types.Integer)


class Area(KNXMixin, Base):
    """ORM for xknx 'DPTArea'.

    DType: DPST-14-10
    """

    __tablename__ = "area"
    value = Column(types.Float)


class Binary(KNXMixin, Base):
    """ORM for xknx 'DPTBinary'.

    DType: DPT-1, DPST-1-1, DPST-1-2, DPST-1-3, DPST-1-5, DPST-1-6, DPST-1-7, DPST-1-8, DPST-1-9, DPST-1-10, DPST-1-11, DPST-1-15, DPST-1-16, DPST-1-17, DPST-1-19, DPST-1-23
    """

    __tablename__ = "binary"
    value = Column(types.Integer)


class Brightness(KNXMixin, Base):
    """ORM for xknx 'DPTBrightness'.

    DType: DPST-7-13
    """

    __tablename__ = "brightness"
    value = Column(types.Integer)


class Capacitance(KNXMixin, Base):
    """ORM for xknx 'DPTCapacitance'.

    DType: DPST-14-11
    """

    __tablename__ = "capacitance"
    value = Column(types.Float)


class ChargeDensitySurface(KNXMixin, Base):
    """ORM for xknx 'DPTChargeDensitySurface'.

    DType: DPST-14-12
    """

    __tablename__ = "chargedensitysurface"
    value = Column(types.Float)


class ChargeDensityVolume(KNXMixin, Base):
    """ORM for xknx 'DPTChargeDensityVolume'.

    DType: DPST-14-13
    """

    __tablename__ = "chargedensityvolume"
    value = Column(types.Float)


class ColorTemperature(KNXMixin, Base):
    """ORM for xknx 'DPTColorTemperature'.

    DType: DPST-7-600
    """

    __tablename__ = "colortemperature"
    value = Column(types.Integer)


class CommonTemperature(KNXMixin, Base):
    """ORM for xknx 'DPTCommonTemperature'.

    DType: DPST-14-68
    """

    __tablename__ = "commontemperature"
    value = Column(types.Float)


class Compressibility(KNXMixin, Base):
    """ORM for xknx 'DPTCompressibility'.

    DType: DPST-14-14
    """

    __tablename__ = "compressibility"
    value = Column(types.Float)


class Conductance(KNXMixin, Base):
    """ORM for xknx 'DPTConductance'.

    DType: DPST-14-15
    """

    __tablename__ = "conductance"
    value = Column(types.Float)


class ControlStepwise(KNXMixin, Base):
    """ORM for xknx 'DPTControlStepwise'.

    DType: DPT-3
    """

    __tablename__ = "controlstepwise"
    value = Column(types.Integer)


class ControlStepwiseBlinds(KNXMixin, Base):
    """ORM for xknx 'DPTControlStepwiseBlinds'.

    DType: DPST-3-8
    """

    __tablename__ = "controlstepwiseblinds"
    value = Column(types.Integer)


class ControlStepwiseDimming(KNXMixin, Base):
    """ORM for xknx 'DPTControlStepwiseDimming'.

    DType: DPST-3-7
    """

    __tablename__ = "controlstepwisedimming"
    value = Column(types.Integer)


class Current(KNXMixin, Base):
    """ORM for xknx 'DPTCurrent'.

    DType: DPST-9-21
    """

    __tablename__ = "current"
    value = Column(types.Float)


class Date(KNXMixin, Base):
    """ORM for xknx 'DPTDate'.

    DType: DPST-11-1
    """

    __tablename__ = "date"
    value = Column(types.Date)


class DateTime(KNXMixin, Base):
    """ORM for xknx 'DPTDateTime'.

    DType: DPST-19-1
    """

    __tablename__ = "datetime"
    value = Column(types.DateTime)


class DecimalFactor(KNXMixin, Base):
    """ORM for xknx 'DPTDecimalFactor'.

    DType: DPST-5-5
    """

    __tablename__ = "decimalfactor"
    value = Column(types.Integer)


class DeltaTimeHrs(KNXMixin, Base):
    """ORM for xknx 'DPTDeltaTimeHrs'.

    DType: DPST-8-7
    """

    __tablename__ = "deltatimehrs"
    value = Column(types.Integer)


class DeltaTimeMin(KNXMixin, Base):
    """ORM for xknx 'DPTDeltaTimeMin'.

    DType: DPST-8-6
    """

    __tablename__ = "deltatimemin"
    value = Column(types.Integer)


class DeltaTimeMsec(KNXMixin, Base):
    """ORM for xknx 'DPTDeltaTimeMsec'.

    DType: DPST-8-2
    """

    __tablename__ = "deltatimemsec"
    value = Column(types.Integer)


class DeltaTimeSec(KNXMixin, Base):
    """ORM for xknx 'DPTDeltaTimeSec'.

    DType: DPST-8-5
    """

    __tablename__ = "deltatimesec"
    value = Column(types.Integer)


class Density(KNXMixin, Base):
    """ORM for xknx 'DPTDensity'.

    DType: DPST-14-17
    """

    __tablename__ = "density"
    value = Column(types.Float)


class ElectricCharge(KNXMixin, Base):
    """ORM for xknx 'DPTElectricCharge'.

    DType: DPST-14-18
    """

    __tablename__ = "electriccharge"
    value = Column(types.Float)


class ElectricCurrent(KNXMixin, Base):
    """ORM for xknx 'DPTElectricCurrent'.

    DType: DPST-14-19
    """

    __tablename__ = "electriccurrent"
    value = Column(types.Float)


class ElectricCurrentDensity(KNXMixin, Base):
    """ORM for xknx 'DPTElectricCurrentDensity'.

    DType: DPST-14-20
    """

    __tablename__ = "electriccurrentdensity"
    value = Column(types.Float)


class ElectricDipoleMoment(KNXMixin, Base):
    """ORM for xknx 'DPTElectricDipoleMoment'.

    DType: DPST-14-21
    """

    __tablename__ = "electricdipolemoment"
    value = Column(types.Float)


class ElectricDisplacement(KNXMixin, Base):
    """ORM for xknx 'DPTElectricDisplacement'.

    DType: DPST-14-22
    """

    __tablename__ = "electricdisplacement"
    value = Column(types.Float)


class ElectricFieldStrength(KNXMixin, Base):
    """ORM for xknx 'DPTElectricFieldStrength'.

    DType: DPST-14-23
    """

    __tablename__ = "electricfieldstrength"
    value = Column(types.Float)


class ElectricFlux(KNXMixin, Base):
    """ORM for xknx 'DPTElectricFlux'.

    DType: DPST-14-24
    """

    __tablename__ = "electricflux"
    value = Column(types.Float)


class ElectricFluxDensity(KNXMixin, Base):
    """ORM for xknx 'DPTElectricFluxDensity'.

    DType: DPST-14-25
    """

    __tablename__ = "electricfluxdensity"
    value = Column(types.Float)


class ElectricPolarization(KNXMixin, Base):
    """ORM for xknx 'DPTElectricPolarization'.

    DType: DPST-14-26
    """

    __tablename__ = "electricpolarization"
    value = Column(types.Float)


class ElectricPotential(KNXMixin, Base):
    """ORM for xknx 'DPTElectricPotential'.

    DType: DPST-14-27
    """

    __tablename__ = "electricpotential"
    value = Column(types.Float)


class ElectricPotentialDifference(KNXMixin, Base):
    """ORM for xknx 'DPTElectricPotentialDifference'.

    DType: DPST-14-28
    """

    __tablename__ = "electricpotentialdifference"
    value = Column(types.Float)


class ElectricalConductivity(KNXMixin, Base):
    """ORM for xknx 'DPTElectricalConductivity'.

    DType: DPST-14-16
    """

    __tablename__ = "electricalconductivity"
    value = Column(types.Float)


class ElectromagneticMoment(KNXMixin, Base):
    """ORM for xknx 'DPTElectromagneticMoment'.

    DType: DPST-14-29
    """

    __tablename__ = "electromagneticmoment"
    value = Column(types.Float)


class ElectromotiveForce(KNXMixin, Base):
    """ORM for xknx 'DPTElectromotiveForce'.

    DType: DPST-14-30
    """

    __tablename__ = "electromotiveforce"
    value = Column(types.Float)


class Energy(KNXMixin, Base):
    """ORM for xknx 'DPTEnergy'.

    DType: DPST-14-31
    """

    __tablename__ = "energy"
    value = Column(types.Float)


class Enthalpy(KNXMixin, Base):
    """ORM for xknx 'DPTEnthalpy'.

    DType: DPST-9-999
    """

    __tablename__ = "enthalpy"
    value = Column(types.Float)


class FlowRateM3H(KNXMixin, Base):
    """ORM for xknx 'DPTFlowRateM3H'.

    DType: DPST-13-2
    """

    __tablename__ = "flowratem3h"
    value = Column(types.Integer)


class Force(KNXMixin, Base):
    """ORM for xknx 'DPTForce'.

    DType: DPST-14-32
    """

    __tablename__ = "force"
    value = Column(types.Float)


class FourByteFloat(KNXMixin, Base):
    """ORM for xknx 'DPT4ByteFloat'.

    DType: DPT-14
    """

    __tablename__ = "fourbytefloat"
    value = Column(types.Float)


class FourByteSigned(KNXMixin, Base):
    """ORM for xknx 'DPT4ByteSigned'.

    DType: DPT-13
    """

    __tablename__ = "fourbytesigned"
    value = Column(types.Integer)


class FourByteUnsigned(KNXMixin, Base):
    """ORM for xknx 'DPT4ByteUnsigned'.

    DType: DPT-12, DPST-27-1, DPST-238-600
    """

    __tablename__ = "fourbyteunsigned"
    value = Column(types.Integer)


class Frequency(KNXMixin, Base):
    """ORM for xknx 'DPTFrequency'.

    DType: DPST-14-33
    """

    __tablename__ = "frequency"
    value = Column(types.Float)


class HVACContrMode(KNXMixin, Base):
    """ORM for xknx 'DPTHVACContrMode'.

    DType: DPST-20-105
    """

    __tablename__ = "hvaccontrmode"
    value = Column(types.Integer)


class HeatCapacity(KNXMixin, Base):
    """ORM for xknx 'DPTHeatCapacity'.

    DType: DPST-14-35
    """

    __tablename__ = "heatcapacity"
    value = Column(types.Float)


class HeatFlowRate(KNXMixin, Base):
    """ORM for xknx 'DPTHeatFlowRate'.

    DType: DPST-14-36
    """

    __tablename__ = "heatflowrate"
    value = Column(types.Float)


class HeatQuantity(KNXMixin, Base):
    """ORM for xknx 'DPTHeatQuantity'.

    DType: DPST-14-37
    """

    __tablename__ = "heatquantity"
    value = Column(types.Float)


class Humidity(KNXMixin, Base):
    """ORM for xknx 'DPTHumidity'.

    DType: DPST-9-7
    """

    __tablename__ = "humidity"
    value = Column(types.Float)


class Impedance(KNXMixin, Base):
    """ORM for xknx 'DPTImpedance'.

    DType: DPST-14-38
    """

    __tablename__ = "impedance"
    value = Column(types.Float)


class KelvinPerPercent(KNXMixin, Base):
    """ORM for xknx 'DPTKelvinPerPercent'.

    DType: DPST-9-23
    """

    __tablename__ = "kelvinperpercent"
    value = Column(types.Float)


class Length(KNXMixin, Base):
    """ORM for xknx 'DPTLength'.

    DType: DPST-14-39
    """

    __tablename__ = "length"
    value = Column(types.Float)


class LengthMm(KNXMixin, Base):
    """ORM for xknx 'DPTLengthMm'.

    DType: DPST-7-11
    """

    __tablename__ = "lengthmm"
    value = Column(types.Integer)


class LightQuantity(KNXMixin, Base):
    """ORM for xknx 'DPTLightQuantity'.

    DType: DPST-14-40
    """

    __tablename__ = "lightquantity"
    value = Column(types.Float)


class LongDeltaTimeSec(KNXMixin, Base):
    """ORM for xknx 'DPTLongDeltaTimeSec'.

    DType: DPST-13-100
    """

    __tablename__ = "longdeltatimesec"
    value = Column(types.Integer)


class Luminance(KNXMixin, Base):
    """ORM for xknx 'DPTLuminance'.

    DType: DPST-14-41
    """

    __tablename__ = "luminance"
    value = Column(types.Float)


class LuminousFlux(KNXMixin, Base):
    """ORM for xknx 'DPTLuminousFlux'.

    DType: DPST-14-42
    """

    __tablename__ = "luminousflux"
    value = Column(types.Float)


class LuminousIntensity(KNXMixin, Base):
    """ORM for xknx 'DPTLuminousIntensity'.

    DType: DPST-14-43
    """

    __tablename__ = "luminousintensity"
    value = Column(types.Float)


class Lux(KNXMixin, Base):
    """ORM for xknx 'DPTLux'.

    DType: DPST-9-4
    """

    __tablename__ = "lux"
    value = Column(types.Float)


class MagneticFieldStrength(KNXMixin, Base):
    """ORM for xknx 'DPTMagneticFieldStrength'.

    DType: DPST-14-44
    """

    __tablename__ = "magneticfieldstrength"
    value = Column(types.Float)


class MagneticFlux(KNXMixin, Base):
    """ORM for xknx 'DPTMagneticFlux'.

    DType: DPST-14-45
    """

    __tablename__ = "magneticflux"
    value = Column(types.Float)


class MagneticFluxDensity(KNXMixin, Base):
    """ORM for xknx 'DPTMagneticFluxDensity'.

    DType: DPST-14-46
    """

    __tablename__ = "magneticfluxdensity"
    value = Column(types.Float)


class MagneticMoment(KNXMixin, Base):
    """ORM for xknx 'DPTMagneticMoment'.

    DType: DPST-14-47
    """

    __tablename__ = "magneticmoment"
    value = Column(types.Float)


class MagneticPolarization(KNXMixin, Base):
    """ORM for xknx 'DPTMagneticPolarization'.

    DType: DPST-14-48
    """

    __tablename__ = "magneticpolarization"
    value = Column(types.Float)


class Magnetization(KNXMixin, Base):
    """ORM for xknx 'DPTMagnetization'.

    DType: DPST-14-49
    """

    __tablename__ = "magnetization"
    value = Column(types.Float)


class MagnetomotiveForce(KNXMixin, Base):
    """ORM for xknx 'DPTMagnetomotiveForce'.

    DType: DPST-14-50
    """

    __tablename__ = "magnetomotiveforce"
    value = Column(types.Float)


class Mass(KNXMixin, Base):
    """ORM for xknx 'DPTMass'.

    DType: DPST-14-51
    """

    __tablename__ = "mass"
    value = Column(types.Float)


class MassFlux(KNXMixin, Base):
    """ORM for xknx 'DPTMassFlux'.

    DType: DPST-14-52
    """

    __tablename__ = "massflux"
    value = Column(types.Float)


class Mol(KNXMixin, Base):
    """ORM for xknx 'DPTMol'.

    DType: DPST-14-4
    """

    __tablename__ = "mol"
    value = Column(types.Float)


class Momentum(KNXMixin, Base):
    """ORM for xknx 'DPTMomentum'.

    DType: DPST-14-53
    """

    __tablename__ = "momentum"
    value = Column(types.Float)


class PartsPerMillion(KNXMixin, Base):
    """ORM for xknx 'DPTPartsPerMillion'.

    DType: DPST-9-8
    """

    __tablename__ = "partspermillion"
    value = Column(types.Float)


class PercentU8(KNXMixin, Base):
    """ORM for xknx 'DPTPercentU8'.

    DType: DPST-5-4
    """

    __tablename__ = "percentu8"
    value = Column(types.Integer)


class PercentV16(KNXMixin, Base):
    """ORM for xknx 'DPTPercentV16'.

    DType: DPST-8-10
    """

    __tablename__ = "percentv16"
    value = Column(types.Integer)


class PercentV8(KNXMixin, Base):
    """ORM for xknx 'DPTPercentV8'.

    DType: DPST-6-1
    """

    __tablename__ = "percentv8"
    value = Column(types.Integer)


class PhaseAngleDeg(KNXMixin, Base):
    """ORM for xknx 'DPTPhaseAngleDeg'.

    DType: DPST-14-55
    """

    __tablename__ = "phaseangledeg"
    value = Column(types.Float)


class PhaseAngleRad(KNXMixin, Base):
    """ORM for xknx 'DPTPhaseAngleRad'.

    DType: DPST-14-54
    """

    __tablename__ = "phaseanglerad"
    value = Column(types.Float)


class Power(KNXMixin, Base):
    """ORM for xknx 'DPTPower2Byte'.

    DType: DPST-9-24, DPST-14-56
    """

    __tablename__ = "power"
    value = Column(types.Float)


class PowerDensity(KNXMixin, Base):
    """ORM for xknx 'DPTPowerDensity'.

    DType: DPST-9-22
    """

    __tablename__ = "powerdensity"
    value = Column(types.Float)


class PowerFactor(KNXMixin, Base):
    """ORM for xknx 'DPTPowerFactor'.

    DType: DPST-14-57
    """

    __tablename__ = "powerfactor"
    value = Column(types.Float)


class Pressure(KNXMixin, Base):
    """ORM for xknx 'DPTPressure2Byte'.

    DType: DPST-9-6, DPST-14-58
    """

    __tablename__ = "pressure"
    value = Column(types.Float)


class RainAmount(KNXMixin, Base):
    """ORM for xknx 'DPTRainAmount'.

    DType: DPST-9-26
    """

    __tablename__ = "rainamount"
    value = Column(types.Float)


class Reactance(KNXMixin, Base):
    """ORM for xknx 'DPTReactance'.

    DType: DPST-14-59
    """

    __tablename__ = "reactance"
    value = Column(types.Float)


class ReactiveEnergy(KNXMixin, Base):
    """ORM for xknx 'DPTReactiveEnergy'.

    DType: DPST-13-12
    """

    __tablename__ = "reactiveenergy"
    value = Column(types.Integer)


class ReactiveEnergykVARh(KNXMixin, Base):
    """ORM for xknx 'DPTReactiveEnergykVARh'.

    DType: DPST-13-15
    """

    __tablename__ = "reactiveenergykvarh"
    value = Column(types.Integer)


class Resistance(KNXMixin, Base):
    """ORM for xknx 'DPTResistance'.

    DType: DPST-14-60
    """

    __tablename__ = "resistance"
    value = Column(types.Float)


class Resistivity(KNXMixin, Base):
    """ORM for xknx 'DPTResistivity'.

    DType: DPST-14-61
    """

    __tablename__ = "resistivity"
    value = Column(types.Float)


class RotationAngle(KNXMixin, Base):
    """ORM for xknx 'DPTRotationAngle'.

    DType: DPST-8-11
    """

    __tablename__ = "rotationangle"
    value = Column(types.Integer)


class Scaling(KNXMixin, Base):
    """ORM for xknx 'DPTScaling'.

    DType: DPST-5-1
    """

    __tablename__ = "scaling"
    value = Column(types.Integer)


class SceneNumber(KNXMixin, Base):
    """ORM for xknx 'DPTSceneNumber'.

    DType: DPST-17-1, DPST-18-1
    """

    __tablename__ = "scenenumber"
    value = Column(types.Integer)


class SelfInductance(KNXMixin, Base):
    """ORM for xknx 'DPTSelfInductance'.

    DType: DPST-14-62
    """

    __tablename__ = "selfinductance"
    value = Column(types.Float)


class SignedRelativeValue(KNXMixin, Base):
    """ORM for xknx 'DPTSignedRelativeValue'.

    DType: DPT-6, DPST-6-20
    """

    __tablename__ = "signedrelativevalue"
    value = Column(types.Integer)


class SolidAngle(KNXMixin, Base):
    """ORM for xknx 'DPTSolidAngle'.

    DType: DPST-14-63
    """

    __tablename__ = "solidangle"
    value = Column(types.Float)


class SoundIntensity(KNXMixin, Base):
    """ORM for xknx 'DPTSoundIntensity'.

    DType: DPST-14-64
    """

    __tablename__ = "soundintensity"
    value = Column(types.Float)


class Speed(KNXMixin, Base):
    """ORM for xknx 'DPTSpeed'.

    DType: DPST-14-65
    """

    __tablename__ = "speed"
    value = Column(types.Float)


class Stress(KNXMixin, Base):
    """ORM for xknx 'DPTStress'.

    DType: DPST-14-66
    """

    __tablename__ = "stress"
    value = Column(types.Float)


class String(KNXMixin, Base):
    """ORM for xknx 'DPTString'.

    DType: DPST-16-0, DPST-16-1
    """

    __tablename__ = "string"
    value = Column(types.String(14))


class SurfaceTension(KNXMixin, Base):
    """ORM for xknx 'DPTSurfaceTension'.

    DType: DPST-14-67
    """

    __tablename__ = "surfacetension"
    value = Column(types.Float)


class Tariff(KNXMixin, Base):
    """ORM for xknx 'DPTTariff'.

    DType: DPST-5-6
    """

    __tablename__ = "tariff"
    value = Column(types.Integer)


class Temperature(KNXMixin, Base):
    """ORM for xknx 'DPTTemperature'.

    DType: DPST-9-1
    """

    __tablename__ = "temperature"
    value = Column(types.Float)


class TemperatureA(KNXMixin, Base):
    """ORM for xknx 'DPTTemperatureA'.

    DType: DPST-9-3
    """

    __tablename__ = "temperaturea"
    value = Column(types.Float)


class TemperatureDifference(KNXMixin, Base):
    """ORM for xknx 'DPTTemperatureDifference2Byte'.

    DType: DPST-9-2, DPST-14-70
    """

    __tablename__ = "temperaturedifference"
    value = Column(types.Float)


class TemperatureF(KNXMixin, Base):
    """ORM for xknx 'DPTTemperatureF'.

    DType: DPST-9-27
    """

    __tablename__ = "temperaturef"
    value = Column(types.Float)


class ThermalCapacity(KNXMixin, Base):
    """ORM for xknx 'DPTThermalCapacity'.

    DType: DPST-14-71
    """

    __tablename__ = "thermalcapacity"
    value = Column(types.Float)


class ThermalConductivity(KNXMixin, Base):
    """ORM for xknx 'DPTThermalConductivity'.

    DType: DPST-14-72
    """

    __tablename__ = "thermalconductivity"
    value = Column(types.Float)


class ThermoelectricPower(KNXMixin, Base):
    """ORM for xknx 'DPTThermoelectricPower'.

    DType: DPST-14-73
    """

    __tablename__ = "thermoelectricpower"
    value = Column(types.Float)


class Time(KNXMixin, Base):
    """ORM for xknx 'DPTTime'.

    DType: DPST-10-1
    """

    __tablename__ = "time"
    value = Column(types.Time)


class Time1(KNXMixin, Base):
    """ORM for xknx 'DPTTime1'.

    DType: DPST-9-10
    """

    __tablename__ = "time1"
    value = Column(types.Float)


class Time2(KNXMixin, Base):
    """ORM for xknx 'DPTTime2'.

    DType: DPST-9-11
    """

    __tablename__ = "time2"
    value = Column(types.Float)


class TimePeriod100Msec(KNXMixin, Base):
    """ORM for xknx 'DPTTimePeriod100Msec'.

    DType: DPST-7-4
    """

    __tablename__ = "timeperiod100msec"
    value = Column(types.Integer)


class TimePeriod10Msec(KNXMixin, Base):
    """ORM for xknx 'DPTTimePeriod10Msec'.

    DType: DPST-7-3
    """

    __tablename__ = "timeperiod10msec"
    value = Column(types.Integer)


class TimePeriodHrs(KNXMixin, Base):
    """ORM for xknx 'DPTTimePeriodHrs'.

    DType: DPST-7-7
    """

    __tablename__ = "timeperiodhrs"
    value = Column(types.Integer)


class TimePeriodMin(KNXMixin, Base):
    """ORM for xknx 'DPTTimePeriodMin'.

    DType: DPST-7-6
    """

    __tablename__ = "timeperiodmin"
    value = Column(types.Integer)


class TimePeriodMsec(KNXMixin, Base):
    """ORM for xknx 'DPTTimePeriodMsec'.

    DType: DPST-7-2
    """

    __tablename__ = "timeperiodmsec"
    value = Column(types.Integer)


class TimePeriodSec(KNXMixin, Base):
    """ORM for xknx 'DPTTimePeriodSec'.

    DType: DPST-7-5
    """

    __tablename__ = "timeperiodsec"
    value = Column(types.Integer)


class TimeSeconds(KNXMixin, Base):
    """ORM for xknx 'DPTTimeSeconds'.

    DType: DPST-14-74
    """

    __tablename__ = "timeseconds"
    value = Column(types.Float)


class Torque(KNXMixin, Base):
    """ORM for xknx 'DPTTorque'.

    DType: DPST-14-75
    """

    __tablename__ = "torque"
    value = Column(types.Float)


class TwoByteFloat(KNXMixin, Base):
    """ORM for xknx 'DPT2ByteFloat'.

    DType: DPT-9
    """

    __tablename__ = "twobytefloat"
    value = Column(types.Float)


class TwoByteSigned(KNXMixin, Base):
    """ORM for xknx 'DPT2ByteSigned'.

    DType: DPT-8
    """

    __tablename__ = "twobytesigned"
    value = Column(types.Integer)


class TwoByteUnsigned(KNXMixin, Base):
    """ORM for xknx 'DPT2ByteUnsigned'.

    DType: DPT-7
    """

    __tablename__ = "twobyteunsigned"
    value = Column(types.Integer)


class TwoUcount(KNXMixin, Base):
    """ORM for xknx 'DPT2Ucount'.

    DType: DPST-7-1
    """

    __tablename__ = "twoucount"
    value = Column(types.Integer)


class UElCurrentmA(KNXMixin, Base):
    """ORM for xknx 'DPTUElCurrentmA'.

    DType: DPST-7-12
    """

    __tablename__ = "uelcurrentma"
    value = Column(types.Integer)


class Value1ByteUnsigned(KNXMixin, Base):
    """ORM for xknx 'DPTValue1ByteUnsigned'.

    DType: DPT-5
    """

    __tablename__ = "value1byteunsigned"
    value = Column(types.Integer)


class Value1Count(KNXMixin, Base):
    """ORM for xknx 'DPTValue1Count'.

    DType: DPST-6-10
    """

    __tablename__ = "value1count"
    value = Column(types.Integer)


class Value1Ucount(KNXMixin, Base):
    """ORM for xknx 'DPTValue1Ucount'.

    DType: DPST-2-1, DPST-5-10, DPST-21-1
    """

    __tablename__ = "value1ucount"
    value = Column(types.Integer)


class Value2Count(KNXMixin, Base):
    """ORM for xknx 'DPTValue2Count'.

    DType: DPST-8-1
    """

    __tablename__ = "value2count"
    value = Column(types.Integer)


class Value4Count(KNXMixin, Base):
    """ORM for xknx 'DPTValue4Count'.

    DType: DPST-13-1
    """

    __tablename__ = "value4count"
    value = Column(types.Integer)


class Voltage(KNXMixin, Base):
    """ORM for xknx 'DPTVoltage'.

    DType: DPST-9-20
    """

    __tablename__ = "voltage"
    value = Column(types.Float)


class Volume(KNXMixin, Base):
    """ORM for xknx 'DPTVolume'.

    DType: DPST-14-76
    """

    __tablename__ = "volume"
    value = Column(types.Float)


class VolumeFlow(KNXMixin, Base):
    """ORM for xknx 'DPTVolumeFlow'.

    DType: DPST-9-25
    """

    __tablename__ = "volumeflow"
    value = Column(types.Float)


class VolumeFlux(KNXMixin, Base):
    """ORM for xknx 'DPTVolumeFlux'.

    DType: DPST-14-77
    """

    __tablename__ = "volumeflux"
    value = Column(types.Float)


class Weight(KNXMixin, Base):
    """ORM for xknx 'DPTWeight'.

    DType: DPST-14-78
    """

    __tablename__ = "weight"
    value = Column(types.Float)


class Work(KNXMixin, Base):
    """ORM for xknx 'DPTWork'.

    DType: DPST-14-79
    """

    __tablename__ = "work"
    value = Column(types.Float)


class Wsp(KNXMixin, Base):
    """ORM for xknx 'DPTWsp'.

    DType: DPST-9-5
    """

    __tablename__ = "wsp"
    value = Column(types.Float)


class WspKmh(KNXMixin, Base):
    """ORM for xknx 'DPTWspKmh'.

    DType: DPST-9-28
    """

    __tablename__ = "wspkmh"
    value = Column(types.Float)
