[tool.poetry]
name = "logger"
version = "0.3.0" # Also update in logger/__init__.py AND projects
description = "Log knx messages"
authors = ["Fabian Göttel <fabian.goettel@gmail.com>"]

[tool.poetry.dependencies]
python = "3.10"
SQLAlchemy = "^1.4"
xknx = "^0.18"
psycopg-binary = { version = "^3.0", optional = true }

[tool.poetry.extras]
pgsql = ["psycopg3-binary"]

[tool.poetry.dev-dependencies]
black = "^21.7b0"
isort = "^5.10"
mypy = "^0.910"
pydocstyle = "^6.1.1"
pylint = "^2.11"
pytest = "^6.2"
pytest-asyncio = "^0.16"
pytest-cov = "^3.0"
pytest-mock = "^3.6"
pytest-profiling = "^1.7"
sqlalchemy-stubs = "^0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.10"

[[tool.mypy.overrides]]
module = "logger.orm"
ignore_errors = true

[tool.pydocstyle]
ignore = [
    "D202",
    "D203",
    "D213",
    "D416",
]

[tool.coverage]
source = ["logger"]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "def __str__",
    "if __name__ == .__main__.:",
    "pytest.main([.-x.])",
]
omit = ["logger/codegen"]