[tool.poetry]
name = "logger"
version = "0.0.1" # Also update in logger/__init__.px
description = "Log knx messages"
authors = ["Fabian Göttel <fabian.goettel@gmail.com>"]

[tool.poetry.dependencies]
python = "3.10"
SQLAlchemy = "^1.4"
xknx = "^0.18.7"
psycopg2-binary = { version = "^2.8.6", optional = true }

[tool.poetry.extras]
pgsql = ["psycopg2-binary"]

[tool.poetry.dev-dependencies]
black = "^21.7b0"
isort = "^5.9.2"
mypy = "^0.910"
pydocstyle = "^6.1.1"
pylint = "^2.9.5"
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"
pytest-cov = "^2.12.1"
pytest-mock = "^3.6.1"
pytest-profiling = "^1.7.0"
sqlalchemy-stubs = "^0.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = 3.9

[[tool.mypy.overrides]]
module = "logger.orm"
ignore_errors = true

[tool.pydocstyle]
ignore = [
    "D202",
    "D203",
    "D213",
    "D416",
]

[tool.coverage]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
]
source = ["logger"]
omit = ["logger/codegen"]