[tool.poetry]
name = "logger"
version = "0.4.0" # Also update in logger/__init__.py AND projects
description = "Log knx messages"
authors = ["Fabian Göttel <fabian.goettel@gmail.com>"]

[tool.poetry.dependencies]
python = "3.10"
SQLAlchemy = "*"
xknx = "*"
psycopg-binary = { version = "*", optional = true }

[tool.poetry.extras]
pgsql = ["psycopg3-binary"]

[tool.poetry.dev-dependencies]
black = "*"
isort = "*"
mypy = "*"
pydocstyle = "*"
pylint = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "*"
pytest-mock = "*"
pytest-profiling = "*"
sqlalchemy-stubs = "*"
toml = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.10"

[[tool.mypy.overrides]]
module = "logger.orm"
ignore_errors = true

[tool.pydocstyle]
ignore = [
    "D202",
    "D203",
    "D213",
    "D416",
]

[tool.pytest.ini_options]
testpaths = [
    "test",
]
asyncio_mode = "auto"

[tool.coverage]
source = ["logger"]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "def __str__",
    "if __name__ == .__main__.:",
    "pytest.main([.-x.])",
]
omit = ["logger/codegen"]