name: ga_generator-lint-and-test

on:
  push:
    paths:
      - 'ga_generator/**'
      - '.github/workflows/ga_generator_actions.yml'

jobs:
  tests:
    strategy:
      matrix:
        python: ["3.12"]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ga_generator
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        architecture: x64
    - run: pip install poetry==1.8.4
    - run: make install
    - run: make test
    - run: make lint
