name: logger-lint-and-test

on:
  push:
    paths:
      - 'logger/**'
      - '.github/workflows/logger_actions.yml'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.10"
        architecture: x64
    - run: pip install nox==2022.1.7
    - run: pip install poetry==1.1.11
    - run: nox