name: logger-lint-and-test

on:
  push:
    paths:
      - 'logger/**'
      - '.github/workflows/logger_actions.yml'
  pull_request:

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: 1.1.11
  PYLINTHOME: ${{ github.workspace }}/.pylint_cache
  MYPY_CACHE_DIR: ${{ github.workspace }}/.mypy_cache
  POETRY_CACHE_DIR: ${{ github.workspace }}/.poetry_cache
  WORKFLOW_VERSION: 5

jobs:
  lint-and-test: # TODO: Split into lint and test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # TODO: unix by default, windows only for merges to master
    runs-on: ${{ matrix.os}}
    defaults:
      run:
        working-directory: ./logger
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Cache Poetry
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}-${{ env.WORKFLOW_VERSION }}
      - name: Cache Poetry packages
        uses: actions/cache@v2
        with:
          path: ${{ env.POETRY_CACHE_DIR }}
          key: poetry-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}-${{ env.WORKFLOW_VERSION }}
      - name: Cache Pylint
        uses: actions/cache@v2
        with:
          path: ${{ env.PYLINTHOME }}
          key: pylint-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}-${{ env.WORKFLOW_VERSION }}
      - name: Cache mypy
        uses: actions/cache@v2
        with:
          path: ${{ env.MYPY_CACHE_DIR }}
          key: mypy-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}-${{ env.WORKFLOW_VERSION }}
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run poetry image
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Add project dependencies
        run: poetry install
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
