name: logger-lint-and-test

on:
  pull_request:
    paths:
      - 'logger/**'
      - '.github/workflows/logger_actions.yml'
    branches:
     -main

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: 1.1.11

jobs:
  lint-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os}}
    defaults:
     run:
        working-directory: ./logger
    steps:
      - uses: actions/knx-composite-action
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
