name: logger-lint-and-test

on:
  push:
    paths:
      - 'logger/**'
      - '.github/workflows/logger_actions.yml'

jobs:
  tests:
    strategy:
      matrix:
        python: ["3.11"]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./logger
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        architecture: x64
    - run: pip install poetry==1.3.1
    - run: pip install nox==2022.11.21
    - run: pip install nox_poetry==1.0.2
    - run: nox --python ${{ matrix.python }}