name: logger-lint-and-test

on:
  push:
    paths:
      - 'logger/**'
      - '.github/workflows/logger_actions.yml'

jobs:
  tests:
    strategy:
      matrix:
        python: ["3.12"]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./logger
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        architecture: x64
    - run: pip install poetry==1.8.4
    - run: pip install nox==2024.10.9
    - run: pip install nox_poetry==1.0.3
    - run: nox --python ${{ matrix.python }}