name: projects-lint-and-test

on:
  push:
    paths:
      - 'projects/**'
      - '.github/workflows/projects_actions.yml'

jobs:
  nox:
    strategy:
      matrix:
        python: ["3.12"]
        session: ["tests", "lint", "mypy"]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projects
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
        architecture: x64
    - run: pip install poetry==1.8.4
    - run: pip install nox==2024.10.9
    - run: pip install nox_poetry==1.0.3
    - run: nox --python ${{ matrix.python }} --session ${{ matrix.session }}
