name: projects-lint-and-test

on:
  push:
    paths:
      - 'projects/**'
      - '.github/workflows/projects_actions.yml'

jobs:
  tests:
    strategy:
      matrix:
        python: ["3.9", "3.10"]
        session: ["tests", "lint", "mypy", "safety"]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./logger
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
        architecture: x64
    - run: pip install poetry==1.1.11
    - run: pip install nox==2022.8.7
    - run: pip install nox_poetry==1.0.1
    - run: nox --python ${{ matrix.python }} --session ${{ matrix.session }}
