name: logger-codegen-and-lint-and-test

on: [push]

env:
  PYTHON_VERSION: "3.10"
  POETRY_VERSION: 1.1.11

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./logger
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Cache Poetry cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}
      - name: Cache Packages
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/*.yml') }}
      - name: Cache Pylint
        uses: actions/cache@v2
        with:
          path: ~/.cache/pylint
          key: pylint-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}
      - name: Cache mypy
        uses: actions/cache@v2
        with:
          path: .mypy_cache
          key: mypy-cache-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ env.POETRY_VERSION }}
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run poetry image
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Add project dependencies
        run: poetry install
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
