name: logger-actions
on: [push]
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./logger
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Run poetry image
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: 1.1.11
      - name: Show poetry version
        run: poetry --version
      - name: Add project dependencies
        run: poetry install
      - name: Run tests
        run: make test

